# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_select_camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_select_camera(object):
    def setupUi(self, dialog_select_camera):
        dialog_select_camera.setObjectName("dialog_select_camera")
        dialog_select_camera.resize(382, 72)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/baseline_search_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog_select_camera.setWindowIcon(icon)
        dialog_select_camera.setStyleSheet("background-color: rgb(120, 149, 165);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(dialog_select_camera)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.command_link_button_vimba = QtWidgets.QCommandLinkButton(dialog_select_camera)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 149, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.command_link_button_vimba.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.command_link_button_vimba.setFont(font)
        self.command_link_button_vimba.setFocusPolicy(QtCore.Qt.NoFocus)
        self.command_link_button_vimba.setAutoRepeat(False)
        self.command_link_button_vimba.setObjectName("command_link_button_vimba")
        self.horizontalLayout.addWidget(self.command_link_button_vimba)
        self.command_link_button_andor = QtWidgets.QCommandLinkButton(dialog_select_camera)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.command_link_button_andor.setFont(font)
        self.command_link_button_andor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.command_link_button_andor.setObjectName("command_link_button_andor")
        self.horizontalLayout.addWidget(self.command_link_button_andor)

        self.retranslateUi(dialog_select_camera)
        QtCore.QMetaObject.connectSlotsByName(dialog_select_camera)

    def retranslateUi(self, dialog_select_camera):
        _translate = QtCore.QCoreApplication.translate
        dialog_select_camera.setWindowTitle(_translate("dialog_select_camera", "Select camera"))
        self.command_link_button_vimba.setText(_translate("dialog_select_camera", "Vimba"))
        self.command_link_button_andor.setText(_translate("dialog_select_camera", "Andor"))
import icon_resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_select_camera = QtWidgets.QDialog()
    ui = Ui_dialog_select_camera()
    ui.setupUi(dialog_select_camera)
    dialog_select_camera.show()
    sys.exit(app.exec_())
