# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_select_camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_select_camera(object):
    def setupUi(self, dialog_select_camera):
        dialog_select_camera.setObjectName("dialog_select_camera")
        dialog_select_camera.resize(368, 66)
        dialog_select_camera.setStyleSheet("background-color: rgb(120, 149, 165);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(dialog_select_camera)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.command_link_button_vimba = QtWidgets.QCommandLinkButton(dialog_select_camera)
        self.command_link_button_vimba.setObjectName("command_link_button_vimba")
        self.horizontalLayout.addWidget(self.command_link_button_vimba)
        self.command_link_button_andor = QtWidgets.QCommandLinkButton(dialog_select_camera)
        self.command_link_button_andor.setObjectName("command_link_button_andor")
        self.horizontalLayout.addWidget(self.command_link_button_andor)

        self.retranslateUi(dialog_select_camera)
        QtCore.QMetaObject.connectSlotsByName(dialog_select_camera)

    def retranslateUi(self, dialog_select_camera):
        _translate = QtCore.QCoreApplication.translate
        dialog_select_camera.setWindowTitle(_translate("dialog_select_camera", "Select camera"))
        self.command_link_button_vimba.setText(_translate("dialog_select_camera", "Vimba"))
        self.command_link_button_andor.setText(_translate("dialog_select_camera", "Andor"))
import icon_resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_select_camera = QtWidgets.QDialog()
    ui = Ui_dialog_select_camera()
    ui.setupUi(dialog_select_camera)
    dialog_select_camera.show()
    sys.exit(app.exec_())
