# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_image_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_image_menu(object):
    def setupUi(self, interface_image_menu):
        interface_image_menu.setObjectName("interface_image_menu")
        interface_image_menu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(interface_image_menu)
        self.centralwidget.setObjectName("centralwidget")
        interface_image_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(interface_image_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        interface_image_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(interface_image_menu)
        self.statusbar.setObjectName("statusbar")
        interface_image_menu.setStatusBar(self.statusbar)

        self.retranslateUi(interface_image_menu)
        QtCore.QMetaObject.connectSlotsByName(interface_image_menu)

    def retranslateUi(self, interface_image_menu):
        _translate = QtCore.QCoreApplication.translate
        interface_image_menu.setWindowTitle(_translate("interface_image_menu", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface_image_menu = QtWidgets.QMainWindow()
    ui = Ui_interface_image_menu()
    ui.setupUi(interface_image_menu)
    interface_image_menu.show()
    sys.exit(app.exec_())
