# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_camera_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_camera_menu(object):
    def setupUi(self, interface_camera_menu):
        interface_camera_menu.setObjectName("interface_camera_menu")
        interface_camera_menu.resize(800, 600)
        interface_camera_menu.setStyleSheet("QWidget#centralwidget_camera_menu{background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(114, 140, 153, 255), stop:1 rgba(0, 39, 59, 255));}")
        self.centralwidget_camera_menu = QtWidgets.QWidget(interface_camera_menu)
        self.centralwidget_camera_menu.setObjectName("centralwidget_camera_menu")
        interface_camera_menu.setCentralWidget(self.centralwidget_camera_menu)
        self.menubar = QtWidgets.QMenuBar(interface_camera_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        interface_camera_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(interface_camera_menu)
        self.statusbar.setObjectName("statusbar")
        interface_camera_menu.setStatusBar(self.statusbar)

        self.retranslateUi(interface_camera_menu)
        QtCore.QMetaObject.connectSlotsByName(interface_camera_menu)

    def retranslateUi(self, interface_camera_menu):
        _translate = QtCore.QCoreApplication.translate
        interface_camera_menu.setWindowTitle(_translate("interface_camera_menu", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface_camera_menu = QtWidgets.QMainWindow()
    ui = Ui_interface_camera_menu()
    ui.setupUi(interface_camera_menu)
    interface_camera_menu.show()
    sys.exit(app.exec_())
