# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_pattern_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_pattern_menu(object):
    def setupUi(self, interface_pattern_menu):
        interface_pattern_menu.setObjectName("interface_pattern_menu")
        interface_pattern_menu.resize(800, 600)
        interface_pattern_menu.setStyleSheet("QWidget#centralwidget_pattern_menu{background-color: qlineargradient(spread:pad, x1:0, y2:1, x1:1, y1:0, stop:0 rgba(114, 140, 153, 255), stop:1 rgba(22, 59, 77));}")
        self.centralwidget_pattern_menu = QtWidgets.QWidget(interface_pattern_menu)
        self.centralwidget_pattern_menu.setStyleSheet("")
        self.centralwidget_pattern_menu.setObjectName("centralwidget_pattern_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget_pattern_menu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_work = QtWidgets.QWidget(self.centralwidget_pattern_menu)
        self.widget_work.setObjectName("widget_work")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_work)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_for_pattern = QtWidgets.QWidget(self.widget_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_for_pattern.sizePolicy().hasHeightForWidth())
        self.widget_for_pattern.setSizePolicy(sizePolicy)
        self.widget_for_pattern.setObjectName("widget_for_pattern")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_for_pattern)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.companovka_patern = QtWidgets.QGridLayout()
        self.companovka_patern.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.companovka_patern.setSpacing(0)
        self.companovka_patern.setObjectName("companovka_patern")
        self.verticalLayout_4.addLayout(self.companovka_patern)
        self.gridLayout_3.addWidget(self.widget_for_pattern, 0, 0, 20, 1)
        self.textedit_rozy = QtWidgets.QTextEdit(self.widget_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textedit_rozy.sizePolicy().hasHeightForWidth())
        self.textedit_rozy.setSizePolicy(sizePolicy)
        self.textedit_rozy.setMaximumSize(QtCore.QSize(70, 30))
        self.textedit_rozy.setObjectName("textedit_rozy")
        self.gridLayout_3.addWidget(self.textedit_rozy, 5, 3, 1, 1)
        self.textedit_formule_x = QtWidgets.QTextEdit(self.widget_work)
        self.textedit_formule_x.setMaximumSize(QtCore.QSize(180, 30))
        self.textedit_formule_x.setObjectName("textedit_formule_x")
        self.gridLayout_3.addWidget(self.textedit_formule_x, 13, 2, 1, 2)
        self.label_rozy = QtWidgets.QLabel(self.widget_work)
        self.label_rozy.setMinimumSize(QtCore.QSize(50, 50))
        self.label_rozy.setObjectName("label_rozy")
        self.gridLayout_3.addWidget(self.label_rozy, 5, 2, 1, 1)
        self.label_real_horizontal = QtWidgets.QLabel(self.widget_work)
        self.label_real_horizontal.setObjectName("label_real_horizontal")
        self.gridLayout_3.addWidget(self.label_real_horizontal, 4, 2, 1, 1)
        self.label_rozx = QtWidgets.QLabel(self.widget_work)
        self.label_rozx.setObjectName("label_rozx")
        self.gridLayout_3.addWidget(self.label_rozx, 6, 2, 1, 1)
        self.label_real_vertical = QtWidgets.QLabel(self.widget_work)
        self.label_real_vertical.setMinimumSize(QtCore.QSize(50, 50))
        self.label_real_vertical.setObjectName("label_real_vertical")
        self.gridLayout_3.addWidget(self.label_real_vertical, 3, 2, 1, 1)
        self.textedit_real_horizontal_x = QtWidgets.QTextEdit(self.widget_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textedit_real_horizontal_x.sizePolicy().hasHeightForWidth())
        self.textedit_real_horizontal_x.setSizePolicy(sizePolicy)
        self.textedit_real_horizontal_x.setMaximumSize(QtCore.QSize(70, 30))
        self.textedit_real_horizontal_x.setObjectName("textedit_real_horizontal_x")
        self.gridLayout_3.addWidget(self.textedit_real_horizontal_x, 4, 3, 1, 1)
        self.button_simulation = QtWidgets.QPushButton(self.widget_work)
        self.button_simulation.setObjectName("button_simulation")
        self.gridLayout_3.addWidget(self.button_simulation, 8, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 9, 2, 1, 1)
        self.button_approximate = QtWidgets.QPushButton(self.widget_work)
        self.button_approximate.setObjectName("button_approximate")
        self.gridLayout_3.addWidget(self.button_approximate, 14, 2, 1, 2)
        self.textedit_rozx = QtWidgets.QTextEdit(self.widget_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textedit_rozx.sizePolicy().hasHeightForWidth())
        self.textedit_rozx.setSizePolicy(sizePolicy)
        self.textedit_rozx.setMaximumSize(QtCore.QSize(70, 30))
        self.textedit_rozx.setObjectName("textedit_rozx")
        self.gridLayout_3.addWidget(self.textedit_rozx, 6, 3, 1, 1)
        self.textedit_formule_y = QtWidgets.QTextEdit(self.widget_work)
        self.textedit_formule_y.setMaximumSize(QtCore.QSize(180, 30))
        self.textedit_formule_y.setObjectName("textedit_formule_y")
        self.gridLayout_3.addWidget(self.textedit_formule_y, 11, 2, 1, 2)
        self.button_create_pattern = QtWidgets.QPushButton(self.widget_work)
        self.button_create_pattern.setObjectName("button_create_pattern")
        self.gridLayout_3.addWidget(self.button_create_pattern, 7, 2, 1, 2)
        self.label_x_curve = QtWidgets.QLabel(self.widget_work)
        self.label_x_curve.setObjectName("label_x_curve")
        self.gridLayout_3.addWidget(self.label_x_curve, 12, 2, 1, 2)
        self.label_y_curve = QtWidgets.QLabel(self.widget_work)
        self.label_y_curve.setObjectName("label_y_curve")
        self.gridLayout_3.addWidget(self.label_y_curve, 10, 2, 1, 2)
        self.button_import_pattern = QtWidgets.QPushButton(self.widget_work)
        self.button_import_pattern.setMinimumSize(QtCore.QSize(0, 30))
        self.button_import_pattern.setObjectName("button_import_pattern")
        self.gridLayout_3.addWidget(self.button_import_pattern, 1, 2, 1, 1)
        self.button_save_pattern = QtWidgets.QPushButton(self.widget_work)
        self.button_save_pattern.setMinimumSize(QtCore.QSize(0, 30))
        self.button_save_pattern.setObjectName("button_save_pattern")
        self.gridLayout_3.addWidget(self.button_save_pattern, 1, 3, 1, 1)
        self.textedit_real_horizontal_y = QtWidgets.QTextEdit(self.widget_work)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textedit_real_horizontal_y.sizePolicy().hasHeightForWidth())
        self.textedit_real_horizontal_y.setSizePolicy(sizePolicy)
        self.textedit_real_horizontal_y.setMaximumSize(QtCore.QSize(70, 30))
        self.textedit_real_horizontal_y.setObjectName("textedit_real_horizontal_y")
        self.gridLayout_3.addWidget(self.textedit_real_horizontal_y, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.widget_work)
        interface_pattern_menu.setCentralWidget(self.centralwidget_pattern_menu)
        self.menubar = QtWidgets.QMenuBar(interface_pattern_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        interface_pattern_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(interface_pattern_menu)
        self.statusbar.setObjectName("statusbar")
        interface_pattern_menu.setStatusBar(self.statusbar)

        self.retranslateUi(interface_pattern_menu)
        QtCore.QMetaObject.connectSlotsByName(interface_pattern_menu)

    def retranslateUi(self, interface_pattern_menu):
        _translate = QtCore.QCoreApplication.translate
        interface_pattern_menu.setWindowTitle(_translate("interface_pattern_menu", "MainWindow"))
        self.textedit_rozy.setHtml(_translate("interface_pattern_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">7</p></body></html>"))
        self.label_rozy.setText(_translate("interface_pattern_menu", "RozY"))
        self.label_real_horizontal.setText(_translate("interface_pattern_menu", "Real Horizontal X"))
        self.label_rozx.setText(_translate("interface_pattern_menu", "RozX"))
        self.label_real_vertical.setText(_translate("interface_pattern_menu", "Real Vertical Y"))
        self.textedit_real_horizontal_x.setHtml(_translate("interface_pattern_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">423</p></body></html>"))
        self.button_simulation.setText(_translate("interface_pattern_menu", "Simulation"))
        self.button_approximate.setText(_translate("interface_pattern_menu", "Approximate"))
        self.textedit_rozx.setHtml(_translate("interface_pattern_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">9</p></body></html>"))
        self.button_create_pattern.setText(_translate("interface_pattern_menu", "Create patern"))
        self.label_x_curve.setText(_translate("interface_pattern_menu", "X curve:"))
        self.label_y_curve.setText(_translate("interface_pattern_menu", "Y curve:"))
        self.button_import_pattern.setText(_translate("interface_pattern_menu", "Import pattern"))
        self.button_save_pattern.setText(_translate("interface_pattern_menu", "Save pattern"))
        self.textedit_real_horizontal_y.setHtml(_translate("interface_pattern_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">386</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface_pattern_menu = QtWidgets.QMainWindow()
    ui = Ui_interface_pattern_menu()
    ui.setupUi(interface_pattern_menu)
    interface_pattern_menu.show()
    sys.exit(app.exec_())
