# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_image_correction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_image_correction(object):
    def setupUi(self, interface_image_correction):
        interface_image_correction.setObjectName("interface_image_correction")
        interface_image_correction.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/icon2.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        interface_image_correction.setWindowIcon(icon)
        interface_image_correction.setStyleSheet("QWidget#centralwidget_interface_image_correction{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgb(113, 139, 152), stop:0 rgb(40, 75, 92));}\\n\\n")
        self.centralwidget_interface_image_correction = QtWidgets.QWidget(interface_image_correction)
        self.centralwidget_interface_image_correction.setObjectName("centralwidget_interface_image_correction")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget_interface_image_correction)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_dialog_image = QtWidgets.QWidget(self.centralwidget_interface_image_correction)
        self.widget_dialog_image.setObjectName("widget_dialog_image")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_dialog_image)
        self.verticalLayout.setObjectName("verticalLayout")
        self.companovka_dialog_image = QtWidgets.QGridLayout()
        self.companovka_dialog_image.setObjectName("companovka_dialog_image")
        self.verticalLayout.addLayout(self.companovka_dialog_image)
        self.horizontalLayout.addWidget(self.widget_dialog_image)
        self.widget_dialog_controle = QtWidgets.QWidget(self.centralwidget_interface_image_correction)
        self.widget_dialog_controle.setStyleSheet("")
        self.widget_dialog_controle.setObjectName("widget_dialog_controle")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_dialog_controle)
        self.gridLayout.setObjectName("gridLayout")
        self.checkbox_submit_area = QtWidgets.QCheckBox(self.widget_dialog_controle)
        self.checkbox_submit_area.setObjectName("checkbox_submit_area")
        self.gridLayout.addWidget(self.checkbox_submit_area, 1, 0, 1, 1)
        self.button_back_submit = QtWidgets.QPushButton(self.widget_dialog_controle)
        self.button_back_submit.setObjectName("button_back_submit")
        self.gridLayout.addWidget(self.button_back_submit, 2, 0, 1, 1)
        self.button_submit_area = QtWidgets.QPushButton(self.widget_dialog_controle)
        self.button_submit_area.setObjectName("button_submit_area")
        self.gridLayout.addWidget(self.button_submit_area, 1, 1, 1, 1)
        self.button_fit = QtWidgets.QPushButton(self.widget_dialog_controle)
        self.button_fit.setObjectName("button_fit")
        self.gridLayout.addWidget(self.button_fit, 4, 0, 1, 2)
        self.button_forward_submit = QtWidgets.QPushButton(self.widget_dialog_controle)
        self.button_forward_submit.setObjectName("button_forward_submit")
        self.gridLayout.addWidget(self.button_forward_submit, 2, 1, 1, 1)
        self.horizontal_slider_scale = QtWidgets.QSlider(self.widget_dialog_controle)
        self.horizontal_slider_scale.setMaximumSize(QtCore.QSize(250, 16777215))
        self.horizontal_slider_scale.setMinimum(1)
        self.horizontal_slider_scale.setMaximum(100)
        self.horizontal_slider_scale.setPageStep(1)
        self.horizontal_slider_scale.setProperty("value", 50)
        self.horizontal_slider_scale.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_slider_scale.setObjectName("horizontal_slider_scale")
        self.gridLayout.addWidget(self.horizontal_slider_scale, 3, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widget_dialog_controle)
        interface_image_correction.setCentralWidget(self.centralwidget_interface_image_correction)
        self.menubar = QtWidgets.QMenuBar(interface_image_correction)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        interface_image_correction.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(interface_image_correction)
        self.statusbar.setObjectName("statusbar")
        interface_image_correction.setStatusBar(self.statusbar)
        self.action_open_image = QtWidgets.QAction(interface_image_correction)
        self.action_open_image.setObjectName("action_open_image")
        self.action_save_image = QtWidgets.QAction(interface_image_correction)
        self.action_save_image.setObjectName("action_save_image")
        self.menu_file.addAction(self.action_open_image)
        self.menu_file.addAction(self.action_save_image)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(interface_image_correction)
        QtCore.QMetaObject.connectSlotsByName(interface_image_correction)

    def retranslateUi(self, interface_image_correction):
        _translate = QtCore.QCoreApplication.translate
        interface_image_correction.setWindowTitle(_translate("interface_image_correction", "Image correction"))
        self.checkbox_submit_area.setText(_translate("interface_image_correction", "sub area"))
        self.button_back_submit.setText(_translate("interface_image_correction", "Back"))
        self.button_submit_area.setText(_translate("interface_image_correction", "Submit"))
        self.button_fit.setText(_translate("interface_image_correction", "Fit"))
        self.button_forward_submit.setText(_translate("interface_image_correction", "Forward"))
        self.menu_file.setTitle(_translate("interface_image_correction", "File"))
        self.action_open_image.setText(_translate("interface_image_correction", "Open image"))
        self.action_save_image.setText(_translate("interface_image_correction", "Save image"))
import icon_resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface_image_correction = QtWidgets.QMainWindow()
    ui = Ui_interface_image_correction()
    ui.setupUi(interface_image_correction)
    interface_image_correction.show()
    sys.exit(app.exec_())
