# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_image_correction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_image(object):
    def setupUi(self, dialog_image):
        dialog_image.setObjectName("dialog_image")
        dialog_image.resize(838, 598)
        dialog_image.setStyleSheet("QWidget#dialog_image{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgb(113, 139, 152), stop:0 rgb(40, 75, 92));}\\n\\n")
        self.horizontalLayout = QtWidgets.QHBoxLayout(dialog_image)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_dialog_image = QtWidgets.QWidget(dialog_image)
        self.widget_dialog_image.setObjectName("widget_dialog_image")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_dialog_image)
        self.verticalLayout.setObjectName("verticalLayout")
        self.companovka_dialog_image = QtWidgets.QGridLayout()
        self.companovka_dialog_image.setObjectName("companovka_dialog_image")
        self.verticalLayout.addLayout(self.companovka_dialog_image)
        self.horizontalLayout.addWidget(self.widget_dialog_image)
        self.widget_dialog_controle = QtWidgets.QWidget(dialog_image)
        self.widget_dialog_controle.setObjectName("widget_dialog_controle")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_dialog_controle)
        self.gridLayout.setObjectName("gridLayout")
        self.checkbox_submit_area = QtWidgets.QCheckBox(self.widget_dialog_controle)
        self.checkbox_submit_area.setObjectName("checkbox_submit_area")
        self.gridLayout.addWidget(self.checkbox_submit_area, 1, 0, 1, 1)
        self.button_back_submit = QtWidgets.QPushButton(self.widget_dialog_controle)
        self.button_back_submit.setObjectName("button_back_submit")
        self.gridLayout.addWidget(self.button_back_submit, 2, 0, 1, 1)
        self.button_submit_area = QtWidgets.QPushButton(self.widget_dialog_controle)
        self.button_submit_area.setObjectName("button_submit_area")
        self.gridLayout.addWidget(self.button_submit_area, 1, 1, 1, 1)
        self.button_fit = QtWidgets.QPushButton(self.widget_dialog_controle)
        self.button_fit.setObjectName("button_fit")
        self.gridLayout.addWidget(self.button_fit, 4, 0, 1, 2)
        self.button_forward_submit = QtWidgets.QPushButton(self.widget_dialog_controle)
        self.button_forward_submit.setObjectName("button_forward_submit")
        self.gridLayout.addWidget(self.button_forward_submit, 2, 1, 1, 1)
        self.horizontal_slider_scale = QtWidgets.QSlider(self.widget_dialog_controle)
        self.horizontal_slider_scale.setMaximumSize(QtCore.QSize(250, 16777215))
        self.horizontal_slider_scale.setMinimum(1)
        self.horizontal_slider_scale.setMaximum(100)
        self.horizontal_slider_scale.setPageStep(1)
        self.horizontal_slider_scale.setProperty("value", 50)
        self.horizontal_slider_scale.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_slider_scale.setObjectName("horizontal_slider_scale")
        self.gridLayout.addWidget(self.horizontal_slider_scale, 3, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widget_dialog_controle)

        self.retranslateUi(dialog_image)
        QtCore.QMetaObject.connectSlotsByName(dialog_image)

    def retranslateUi(self, dialog_image):
        _translate = QtCore.QCoreApplication.translate
        dialog_image.setWindowTitle(_translate("dialog_image", "Dialog"))
        self.checkbox_submit_area.setText(_translate("dialog_image", "sub area"))
        self.button_back_submit.setText(_translate("dialog_image", "Back"))
        self.button_submit_area.setText(_translate("dialog_image", "Submit"))
        self.button_fit.setText(_translate("dialog_image", "Fit"))
        self.button_forward_submit.setText(_translate("dialog_image", "Forward"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_image = QtWidgets.QDialog()
    ui = Ui_dialog_image()
    ui.setupUi(dialog_image)
    dialog_image.show()
    sys.exit(app.exec_())
